services:
  - type: web
    name: crm-backend
    runtime: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py create_tables && python manage.py seed_data && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: crm-backend-49fn.onrender.com
      - key: CRM_DB_HOST
        fromDatabase:
          name: crm-db
          property: host
      - key: CRM_DB_PORT
        fromDatabase:
          name: crm-db
          property: port
      - key: CRM_DB_NAME
        fromDatabase:
          name: crm-db
          property: database
      - key: CRM_DB_USER
        fromDatabase:
          name: crm-db
          property: user
      - key: CRM_DB_PASSWORD
        fromDatabase:
          name: crm-db
          property: password
      - key: CRM_JWT_SECRET
        generateValue: true
      - key: CRM_OPENAI_API_KEY
        sync: false
      - key: CRM_SCOUT_SECURITY_EMAIL
        sync: false
      - key: CRM_CORS_ORIGINS
        value: https://crm-v2-mu.vercel.app
      - key: CRM_ADMIN_USERNAME
        value: curls
      - key: CRM_ADMIN_EMAIL
        value: Mutukuchristopher562@gmail.com
      - key: CRM_ADMIN_PASSWORD
        value: Jamin$&2222

databases:
  - name: crm-db
    plan: free
    databaseName: crm_v2
    ipAllowList: []
