import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Modal from './Modal';
import Button from './Button';
import { AddClientForm } from './AddClientForm';
import { useAuth } from '../auth/AuthContext';
import { PERMISSIONS } from '../utils/constants';
import { customerDisplayName } from '../utils/customers';

export function AddClientModal({ open, onClose }) {
  const navigate = useNavigate();
  const { hasPermission } = useAuth();
  const [created, setCreated] = useState(null);

  useEffect(() => {
    if (open && !hasPermission(PERMISSIONS.CUSTOMER_CREATE)) onClose();
  }, [open, hasPermission, onClose]);

  useEffect(() => {
    if (!open) setCreated(null);
  }, [open]);

  return (
    <Modal
      open={open}
      onClose={onClose}
      wide
      scrollable
      className="modal--form"
      title={created ? 'Client created' : 'Add Client'}
      labelledBy="add-client-title"
    >
      {created ? (
        <div className="drawer-success">
          <p className="field__hint">The client was saved and assigned a system-generated account number.</p>
          <dl className="def-list">
            <dt>Account number</dt>
            <dd><span className="c360-header__account">{created.account_number}</span></dd>
            <dt>Customer</dt>
            <dd>{customerDisplayName(created)}</dd>
          </dl>
          <p className="field__hint">The account number is generated by the backend and is never typed manually.</p>
          <div className="form-actions">
            <Button variant="secondary" onClick={onClose}>Done</Button>
            <Button variant="primary" onClick={() => navigate(`/customers/${created.customer_id}`)}>
              Open Customer 360
            </Button>
          </div>
        </div>
      ) : (
        <AddClientForm onCreated={setCreated} onCancel={onClose} />
      )}
    </Modal>
  );
}

export default AddClientModal;